site_name: Recon Hunt Queries
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  logo: 'img/shield.png'
nav:
  - Home: index.md
  - Query Tips & Tricks: tips_and_tricks.md
  - General Queries:
    - File Enumeration: general/file_enumeration.md
    - Configuration Audits: general/configuration_audits.md
  - By Tactic:
    - Initial Access: tactics/initial_access.md
    - Execution: tactics/execution.md
    - Persistence: tactics/persistence.md
    - Privilege Escalation: tactics/privilege_escalation.md
    - Defense Evasion: tactics/defense_evasion.md
    - Credential Access: tactics/credential_access.md
    - Discovery: tactics/discovery.md
    - Lateral Movement: tactics/lateral_movement.md
    - Collection: tactics/collection.md
    - Command and Control: tactics/command_and_control.md
    - Exfiltration: tactics/exfiltration.md
    - Impact: tactics/impact.md
  - Reference : reference.md
  
markdown_extensions:
  - codehilite
  - pymdownx.highlight
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

repo_name: 'ReconInfoSec/rhq'
repo_url: 'https://github.com/ReconInfoSec/rhq'

google_analytics: ['UA-86110655-14', 'rhq.reconinfosec.com']